### ISSUE TITLE
Python package pyjwt

### ISSUE THREAD

**Issue by flopp999** [lendy007/skodaconnect#35]
Is it possible for you to change from pyjwt==1.7.1 to pyjwt>=1.7.1?

Then I can upgrade pyjwt to 2.1

https://github.com/lendy007/skodaconnect/blob/5ced4e2a1c7cfcc1c20156568df0058fbcaf7f07/requirements.txt#L5

**Comment by flopp999** [comment]
you are right, all above 1.7.1 make skodaconnect to crash

`DEBUG:skodaconnect.connection:Verifying that tokens are valid now (2021-09-02 07:23:57.072429) and at least until next poll (2021-09-02 07:28:57.072429)
Traceback (most recent call last):
  File "example3.py", line 277, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "example3.py", line 119, in main
    if await connection.doLogin():
  File "/usr/local/lib/python3.7/dist-packages/skodaconnect/connection.py", line 157, in doLogin
    realCars = await self.getRealCarData()
  File "/usr/local/lib/python3.7/dist-packages/skodaconnect/connection.py", line 703, in getRealCarData
    if not await self.validate_tokens:
  File "/usr/local/lib/python3.7/dist-packages/skodaconnect/connection.py", line 1388, in validate_tokens
    id_exp = jwt.decode(idtoken, verify=False).get('exp', None)
  File "/usr/local/lib/python3.7/dist-packages/jwt/api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/jwt/api_jwt.py", line 87, in decode_complete
    'It is required that you pass in a value for the "algorithms" argument when calling decode().'
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
`

**Comment by Farfar** [comment]
I will take a look at the pyJWT documents and see if I can make it work.

**Comment by Farfar** [comment]
Added support for pyJWT 2+ as well as backwards compability. Will be available in 1.1.0 release but available now in latest commit.
