### ISSUE TITLE
Got unhandled error from server: 412

### ISSUE THREAD

**Issue by jfmennedy** [lendy007/skodaconnect#43]
Today skodaconnect (Skoda Octavia RS 2019 Model) stopped working with this error:

Login success!
2021-10-14 13:46:52.628594
Fetching vehicles associated with account.
ERROR:skodaconnect.connection:Got unhandled error from server: 412
DEBUG:skodaconnect.connection:Checking vehicle status_code
Traceback (most recent call last):
  File "C:\Users\me\PycharmProjects\skodaconnect-1.1.6\skodaconnect\connection.py", line 683, in get_vehicles
    vin = vehicle.get('vin', '')
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/me/PycharmProjects/skodaconnect-1.1.6/example/example.py", line 289, in <module>
    loop.run_until_complete(main())
  File "C:\Users\me\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:/Users/me/PycharmProjects/skodaconnect-1.1.6/example/example.py", line 130, in main
    await connection.get_vehicles()
  File "C:\Users\me\PycharmProjects\skodaconnect-1.1.6\skodaconnect\connection.py", line 714, in get_vehicles
    raise SkodaLoginFailedException("Unable to fetch associated vehicles for account")
skodaconnect.exceptions.SkodaLoginFailedException: Unable to fetch associated vehicles for account

Process finished with exit code 1

Yesterday I had to login again with my android skoda app... hopefully they did not change anything again ...

**Comment by jfmennedy** [comment]
Hi, today it was still not working. So i signed out from mobile app and re-signed in. After signing in i was ask to accept the terms of conditions again and now its working again... I´ll keep this in mind if it happens again...
